---
- name: Install s/w applications
  hosts: all
  vars:
   - a: tomcat8
   - b: present
   - c: yes
  tasks:
   - name: Install s/w
     apt:
      name: "{{a}}"
      state: "{{b}}"
      update_cache: "{{c}}"
      
...
