---
- name: Configuring tomcat8
  hosts: all
  tasks:
   - name: Install tomcat8
     apt:
      name: tomcat8
      state: present
      update_cache: yes
   - name: Copy tomcat-users.xml file
     copy:
      src: tomcat-users.xml
      dest: /etc/tomcat8
   - name: Change the port of tomcat from 8080 to 9090
     replace:
      regexp: 8080
      replace: 9090
      path: /etc/tomcat8/server.xml
   - name: Restart tomcat8
     service:
      name: tomcat8
      state: restarted
   - name: Pause the playbook for some time
     pause:
      minutes: 5
   - name: Check the url response of tomcat on server1
     uri:
      url: http://172.31.83.146:9090
      status_code: 200
   - name: Check url response of tomcat on server2
     uri:
      url: http://172.31.86.204:9090
      status_code: 200

